### ISSUE TITLE
MIssing deps in package.json to build

### ISSUE THREAD

**Issue by Alexander-Garcia** [kn1meR/CFB25-Dynasty-Manager#1]
When running `npm i` app fails to build. Missing `framer-motion` and `@radix-ui/react-popover`.

**Comment by kn1meR** [comment]
you will have to run `npm install @radix-ui/react-popover` and `npm install framer-motion` before running.

**Comment by Alexander-Garcia** [comment]
I know. I just wanted to let you know those packages are missing from package.json
